trigger: none

parameters:
- name: 'projectname'
  displayName: 'Project name'
  type: string
  default: 'icp'
- name: 'customername'
  displayName: 'Customer name'
  type: string
  default: ''
- name: 'subscription'
  displayName: 'Azure Subscription'
  type: string
  default: 'icp-service-connection'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: '${{ parameters.subscription }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name "icp-development" --location "West Europe"
      az deployment group create --resource-group "icp-development" --template-file "infra/local_dev_resources.bicep" --parameters project="${{ parameters.projectname }}-${{ parameters.customername}}"
  displayName: 'Deploy Bicep Files'
