trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: 'projectname'
  displayName: 'Project name'
  type: string
  default: 'icp'
- name: 'customername'
  displayName: 'Customer name'
  type: string
  default: ''
- name: 'subscription'
  displayName: 'Azure Service connection name'
  type: string
  default: 'icp-azure-connection'
  values: [icp-azure-connection]
- name: 'git'
  displayName: 'Git Service connection name'
  type: string
  default: 'icp-git-connection'
  values: [icp-git-connection]
- name: 'apiappclientid'
  displayName: 'API App Registration Client ID'
  type: string
  default: 'YOUR_API_APP_REGISTRATION_ID'
- name: 'uiappclientid'
  displayName: 'UI App Registration Client ID'
  type: string
  default: 'YOUR_UI_APP_REGISTRATION_ID'
- name: 'location'
  type: string
  default: 'West Europe'

steps:

- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: '${{ parameters.subscription }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name "icp-runtime" --location "${{ parameters.location }}"
      az deployment group create --resource-group "icp-runtime" --template-file "$(Build.SourcesDirectory)/infra/runtime_resources.bicep" --parameters project="${{ parameters.projectname }}-${{ parameters.customername}}" uiClientId="${{ parameters.uiappclientid }}" apiClientId="${{ parameters.apiappclientid }}"
  displayName: 'Deploy Bicep Files'
