trigger: none

parameters:
- name: 'projectname'
  displayName: 'Project name'
  type: string
  default: 'icp'
- name: 'customername'
  displayName: 'Customer name'
  type: string
  default: ''
- name: 'subscription'
  displayName: 'Azure Service connection name'
  type: string
  default: 'icp-azure-connection'
- name: 'git'
  displayName: 'Git Service connection name'
  type: string
  default: 'icp-git-connection'
- name: 'location'
  type: string
  default: 'West Europe'

resources:
  repositories:
    - repository: icpcore
      type: github
      name: icprelay/icp-core
      ref: refs/tags/v0.1.0
      endpoint: '${{ parameters.git }}'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: icpcore

- task: AzureCLI@2
  displayName: 'Deploy Bicep Files'
  inputs:
    azureSubscription: '${{ parameters.subscription }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -e

      az group create \
        --name "icp-development" \
        --location "${{ parameters.location }}"

      az deployment group create \
        --resource-group "icp-development" \
        --template-file "$(Build.SourcesDirectory)/icp-core/infra/local_dev_resources.bicep" \
        --parameters project="${{ parameters.projectname }}-${{ parameters.customername }}"