trigger: none

resources:
  repositories:
    - repository: icpcore
      type: github
      name: icprelay/icp-core
      ref: refs/tags/v0.1.0
      endpoint: 'icp-git-connection'

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: 'projectname'
  displayName: 'Project name'
  type: string
  default: 'icp'
- name: 'customername'
  displayName: 'Customer name'
  type: string
  default: ''
- name: 'subscription'
  displayName: 'Azure Service connection name'
  type: string
  default: 'icp-azure-connection'
  values: [icp-azure-connection]
- name: 'git'
  displayName: 'Git Service connection name'
  type: string
  default: 'icp-git-connection'
  values: [icp-git-connection]
- name: 'sqladmingroupobjectid'
  displayName: 'ObjectID of ICP SQL Admins Group'
  type: string
  default: 'YOUR_GROUP_OBJECT_ID'
- name: 'sqladmingroupname'
  displayName: 'Display Name of ICP SQL Admins Group'
  type: string
  default: 'icp-sql-admins'
- name: 'location'
  type: string
  default: 'West Europe'

steps:

- checkout: self
- checkout: icpcore

- task: AzureCLI@2
  inputs:
    azureSubscription: '${{ parameters.subscription }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name "icp-persistent" --location "${{ parameters.location }}"
      az deployment group create --resource-group "icp-persistent" --template-file "$(Build.SourcesDirectory)/icp-core/infra/persistent_resources.bicep" --parameters project="${{ parameters.projectname }}-${{ parameters.customername}}" adminObjectId="${{ parameters.sqladmingroupobjectid }}" adminLogin="${{ parameters.sqladmingroupname }}"
  displayName: 'Deploy Bicep Files'
